//////////////////COLORES.INC////////////////////
#define RojoIntenso 0xe70000FF
#define Rojo 0xa80707FF
#define RojoOscuro 0x5b0000FF
#define Azul 0x5FFde2FF
#define Amarillo 0xfce80cFF
#define AmarilloClaro 0xfdfe8bFF
#define Ocre 0xa8961FFA
#define Verde 0x1eb032FF
#define VerdeClaro 0x88dd88FF
#define VerdeOscuro 0x036611FF
#define Naranja 0xff9c00FF
#define NaranjaOscuro 0xb57c01FF
#define Morado 0xC2A2DAFF
#define Violeta 0x694cabFF
#define Gris 0xb0b0b0FF
#define GrisOscuro 0x666666FF
#define Blanco 0xFFFFFFFF
#define Negro 0x000000FF
#define Marron 0x562C2CD2
#define AzulOscuro 0x004d9bFF
#define AzulClaro 0x77c7ffFF
#define Rosa 0xfcc1fdFF // el de chat de admin
#define COLOR_OOCA 0x7bb7b7FF // chat OOC
#define COLOR_OOCB 0x4c9e9eFF // chat OOC
#define COLOR_OOCC 0x2e8787FF // chat OOC
#define COLOR_OOCD 0x187373FF // chat OOC
#define COLOR_OOCE 0x0a5555FF // chat OOC
#define Chat1 0xE6E6E6E6
#define Chat2 0xC8C8C8C8
#define Chat3 0xAAAAAAFF
#define Chat4 0x8C8C8C8C
#define Chat5 0x6E6E6E6E
#define Celeste 0x33CCAAFF
#define Aguamarina 0x00fcffFF
#define AguamarinaOscuro 0x02b1afFF
//////////////////////////////////////////////////////